export const ORDER_REQUEST: 'ORDER_REQUEST' = 'ORDER_REQUEST';
export const ORDER_SUCCESS: 'ORDER_SUCCESS' = 'ORDER_SUCCESS';
export const ORDER_FAILED: 'ORDER_FAILED' = 'ORDER_FAILED';
export const CLEAR_CART: 'CLEAR_CART' = 'CLEAR_CART';

export const INCREASE_TOTAL_PRICE: 'INCREASE_TOTAL_PRICE' = 'INCREASE_TOTAL_PRICE';
export const DECREASE_TOTAL_PRICE: 'DECREASE_TOTAL_PRICE' = 'DECREASE_TOTAL_PRICE';