export const ADD_ITEM_TO_CONSTRUCTOR: 'ADD_ITEM_TO_CONSTRUCTOR' = 'ADD_ITEM_TO_CONSTRUCTOR';
export const DELETE_ITEM_FROM_CONTRUCTOR: 'DELETE_ITEM_FROM_CONTRUCTOR' = 'DELETE_ITEM_FROM_CONTRUCTOR';
export const MOVE_ITEM: 'MOVE_ITEM' = 'MOVE_ITEM';

export const ORDER_REQUEST: 'ORDER_REQUEST' = 'ORDER_REQUEST';
export const ORDER_SUCCESS: 'ORDER_SUCCESS' = 'ORDER_SUCCESS';
export const ORDER_FAILED: 'ORDER_FAILED' = 'ORDER_FAILED';

export const INCREASE_TOTAL_PRICE: 'INCREASE_TOTAL_PRICE' = 'INCREASE_TOTAL_PRICE';
export const DECREASE_TOTAL_PRICE: 'DECREASE_TOTAL_PRICE' = 'DECREASE_TOTAL_PRICE';

export const CLEAR_CART: 'CLEAR_CART' = 'CLEAR_CART';