export const ADD_ITEM_TO_CONSTRUCTOR: 'ADD_ITEM_TO_CONSTRUCTOR' = 'ADD_ITEM_TO_CONSTRUCTOR';
export const DELETE_ITEM_FROM_CONTRUCTOR: 'DELETE_ITEM_FROM_CONTRUCTOR' = 'DELETE_ITEM_FROM_CONTRUCTOR';
export const MOVE_ITEM: 'MOVE_ITEM' = 'MOVE_ITEM';