export const WS_PRIVATE_CONNECT = 'WS_PUBLIC_CONNECT';
export const WS_PRIVATE_CONNECTING = 'WS_PUBLIC_CONNECTING';
export const WS_PRIVATE_SUCCESS = 'WS_PUBLIC_SUCCESS';
export const WS_PRIVATE_ERROR = 'WS_PUBLIC_ERROR';
export const WS_PRIVATE_OPEN = 'WS_PUBLIC_OPEN';
export const WS_PRIVATE_CLOSE = 'WS_PUBLIC_CLOSE';

export const WS_PRIVATE_GET_DATA = 'WS_PUBLIC_GET_DATA';
export const WS_PRIVATE_SEND_DATA = 'WS_PUBLIC_SEND_DATA';