export const WS_PUBLIC_CONNECT = 'WS_PUBLIC_CONNECT';
export const WS_PUBLIC_CONNECTING = 'WS_PUBLIC_CONNECTING';
export const WS_PUBLIC_SUCCESS = 'WS_PUBLIC_SUCCESS';
export const WS_PUBLIC_ERROR = 'WS_PUBLIC_ERROR';
export const WS_PUBLIC_OPEN = 'WS_PUBLIC_OPEN';
export const WS_PUBLIC_CLOSE = 'WS_PUBLIC_CLOSE';

export const WS_PUBLIC_GET_DATA = 'WS_PUBLIC_GET_DATA';
export const WS_PUBLIC_SEND_DATA = 'WS_PUBLIC_SEND_DATA';