export const REGISTER_REQUEST: 'REGISTER_REQUEST' = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';

export const USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST' = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS' = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILED: 'USER_LOGOUT_FAILED' = 'USER_LOGOUT_FAILED';

export const USER_EDIT_REQUEST: 'USER_EDIT_REQUEST' = 'USER_EDIT_REQUEST';
export const USER_EDIT_SUCCESS: 'USER_EDIT_SUCCESS' = 'USER_EDIT_SUCCESS';
export const USER_EDIT_FAILED: 'USER_EDIT_FAILED' = 'USER_EDIT_FAILED';

export const CHECK_USER_REQUEST: 'CHECK_USER_REQUEST' = 'CHECK_USER_REQUEST';
export const CHECK_USER_SUCCESS: 'CHECK_USER_SUCCESS' = 'CHECK_USER_SUCCESS';
export const CHECK_USER_FAILED: 'CHECK_USER_FAILED' = 'CHECK_USER_FAILED';

export const PASS_FORGOT_REQUEST: 'USER_EXISTS_REQUEST' = 'USER_EXISTS_REQUEST';
export const PASS_FORGOT_SUCCESS: 'USER_EXISTS_SUCCESS' = 'USER_EXISTS_SUCCESS';
export const PASS_FORGOT_FAILED: 'USER_EXISTS_FAILED' = 'USER_EXISTS_FAILED';

export const PASS_RESET_REQUEST: 'PASS_RESET_REQUEST' = 'PASS_RESET_REQUEST';
export const PASS_RESET_SUCCESS: 'PASS_RESET_SUCCESS' = 'PASS_RESET_SUCCESS';
export const PASS_RESET_FAILED: 'PASS_RESET_FAILED' = 'PASS_RESET_FAILED';