export enum ModalType {
    INGREDIENT_VIEW = 'INGREDIENT_VIEW',
    ORDER_VIEW = 'ORDER_VIEW',
    ORDER_HISTORY_VIEW = 'ORDER_HISTORY_VIEW',
    ORDER_SUCCESS = 'ORDER_SUCCESS',
    PENDING = 'PENDING'
}